### ISSUE TITLE
Atom feed: Missing layer of html/xml encoding for '<' in title "<3 Deno"

### ISSUE THREAD

**Issue by dennisschagt** [matklad/matklad.github.io#108]
The atom/rss feed currently specifies the title of the latest entry as follows:
```
<title type="html">&lt;3 Deno</title>
```

It looks like an XML decoder will convert the entity `&lt;` into `<`, giving the actual title content:
```
<3 Deno
```

This might look correct at first sight, but the title type is "html", so an RSS reader might interpret this as an unfished tag.
In the case of Newsboat, it results in an empty title.

To correctly encode the title, I think there are two options:
1. Use the same content but specify `type="text"`
2. Add another layer of encoding to make sure that the HTML parser will get `&lt;3 Deno` as input (either encoding the ampersand in `&lt;` as `&amp;`, or using CDATA, e.g.:
    ````
    <title type="html">&amp;lt;3 Deno</title>
    ````

**Comment by matklad** [comment]
Indeed, fixed in https://github.com/matklad/matklad.github.io/commit/338e9aae7c3769380d1b4390422f2501a732b653, thanks!
