### ISSUE TITLE
Cite Norvell

### ISSUE THREAD

**Issue by rljacobson** [matklad/matklad.github.io#15]
I really like [your articles on Pratt parsing](https://github.com/matklad/matklad.github.io/blob/src/_posts/2020-04-13-simple-but-powerful-pratt-parsing.adoc). They have replaced my go-to articles to point people to, at least people who know Rust. 

Your exposition follows [Norvell's](http://www.engr.mun.ca/~theo/Misc/pratt_parsing.htm) pretty closely. I think citing Norvell's articles would be really useful for your readers who want to read more about it. As a bonus, it would serve to acknowledge a primary source like you did with the link to Andy's blog.

**Comment by matklad** [comment]
tbh, I was not familiar with Norvell articles when writing the post. For me, the primary sources were https://www.crockford.com/javascript/tdop/tdop.html and https://journal.stuffwithstuff.com/2011/03/19/pratt-parsers-expression-parsing-made-easy/. In general, I feel like there's so much different presentations of the idea, that the best thing is probably to link to the survey post, and only to the survey post.

So, I am going to close this issue, but thanks for pointing out Norvell articles to me!
