### ISSUE TITLE
SPAG corrections (obligations.dj)

### ISSUE THREAD

**Issue by DoubleHyphen** [matklad/matklad.github.io#156]
“I'd better to follow up” → “I'd better follow up”
“Expectations, but how much?” → “Expectations, but how great?” (Not very sure here)
“against my open soft software” → “against my open-source software” (…presumably?)
“if the answer to the users question” → “if the answer to the users' question“ (Just the apostrophe)
“you, as a maintainer, is responsible” → “you, as a maintainer, are responsible”

I'd have made a pull request, but I can't seem to find the actual source file anywhere.

**Comment by matklad** [comment]
Thanks, fixed!
