### ISSUE TITLE
Pratt parser incorrectly parses strings with syntax errors

### ISSUE THREAD

**Issue by delhoyo31415** [matklad/matklad.github.io#80]
Hello @matklad,

I want to first thank you for your [article](https://matklad.github.io/2020/04/13/simple-but-powerful-pratt-parsing.html) about Pratt parsers, which has helped me to better understand that technique.

However, your code does not work as expected when tested against a string which has mismatched `)` or `]`. For example, the string `1)` is incorrectly parsed as `1` and `4 + 3) * 5` as `(+ 4 3)`.

After looking for a while for the root of the problem, I found that the cause is located in the following function
```rust
fn expr(input: &str) -> S {
    let mut lexer = Lexer::new(input);
    expr_bp(&mut lexer, 0)
}
```

Before implementing parenthesized expressions, `expr_bp(&mut lexer, 0)` returns when the lexer finds `Token::Eof`. After implementing them, when the lexer finds `Token::Op(')')`, it behaves exactly the same as if it has found `Token::Eof`  (it stops calling itself by leaving the `loop`). Therefore, it is possible that `expr_bp(&mut lexer, 0)` returns before the lexer has reached `Token::Eof` so we have to assure it has encountered it.

To fix it, I propose the following modification to `expr` to handle that case

```rust
fn expr(input: &str) -> S {
    let mut lexer = Lexer::new(input);
    let result = expr_bp(&mut lexer, 0);
    if lexer.peek() == Token::Eof {
        result
    } else {
        panic!("Mismatched ')' or ']'");
    }
}
```
Additionally, to see specifically which token is mismatched, you could also do the following

```rust
fn expr(input: &str) -> S {
    let mut lexer = Lexer::new(input);
    let result = expr_bp(&mut lexer, 0);
    match lexer.peek() {
        Token::Eof => result,
        other => panic!("Mismatched '{:?}'", other)
    }
}
```

Now, `expr` panics for the two strings given as example above. Moreover, with that modification, the code still passes all the tests.

**Comment by matklad** [comment]
This is somewhat intentional -- it's a feature that the parser stops at the first "invalid" token.

Typically, you'll invoke `expr` in a context of some larger grammar, so you want the parser to stop at `,`, `;`, `)` and the like.
